name: Continuous Deployment

on:
  push:
    branches:
      - main  # O deploy ocorrerá quando houver commits na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js # Alterar conforme o ambiente (Python, Java, etc)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
      run: |
        echo "$SSH_PRIVATE_KEY" | ssh-add -
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cd $DEPLOY_DIR && git checkout main && docker-compose -f docker-compose.yml down && git pull && docker-compose -f docker-compose.yml up -d --build'