version: '3.8'

services:
  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile-dev
    command: sh -c "npm run start -- --port=3000 --host"
    networks:
      - shared_network

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      OWS_URL: http://ows:8000
    restart: always
    depends_on:
      - postgres
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload --root-path /api"
    ports:
      - "8004:8004"
    expose:
      - "8004"
    networks:
      - shared_network

  ows:
    image: opendatacube/opendatacube:latest
    build:
      context: ./ows
      dockerfile: Dockerfile
    mem_limit: 1g
    environment:
      ODC_DEFAULT_DB_HOSTNAME: postgres
      ODC_DEFAULT_DB_USERNAME: postgres
      ODC_DEFAULT_DB_PASSWORD: opendatacubepassword
      ODC_DEFAULT_DB_DATABASE: postgres
      ODC_DEFAULT_DB_PORT: 5432
      PYTHONPATH: /env/config:/env/lib/python3.12/site-packages
      DATACUBE_OWS_CFG: ows_refactored.dev_af_ows_root_cfg.ows_cfg
      ODC_CONFIG_PATH: /etc/datacube.conf
    volumes:
      - ./data:/data
      - ./ows/products:/env/products
      - ./ows/services/ows_refactored:/env/config/ows_refactored/
      - ./ows/services/inventory:/env/config/inventory/
      - ./ows/output:/env/config/output/
      - ./ows/handle_data_functions:/handle_data_functions
      - ./datacube.conf:/etc/datacube.conf
    ports:
      - "8080:8080"  # Datacube Explorer
      - "8000:8000"  # OWS
    depends_on:
      - postgres
    networks:
      - shared_network
    command: >
      sh -c "
        sleep 10 &&
        datacube system init &&
        cubedash-gen --init --all &&
        gunicorn -b 0.0.0.0:8080 -w 4 'cubedash:create_app()' &
        gunicorn -b 0.0.0.0:8000 --workers=4 --timeout 120 'datacube_ows.wsgi:application'
      "

  postgres:
    image: postgis/postgis:12-2.5-alpine
    mem_limit: 1g
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: opendatacubepassword
      POSTGRES_USER: postgres
    volumes:
      - ./data:/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    networks:
      - shared_network

  cuborizonte:
    build:
      context: nginx/.
      dockerfile: Dockerfile-dev
    depends_on:
      - frontend
      - backend
      - ows
    environment:
      - COPY default.conf.template /etc/nginx/templates/default.conf.template
      - BACKEND_SERVICE=backend
      - FRONTEND_SERVICE=frontend
      - OWS_SERVICE=ows
    volumes:
      - ./data:/usr/share/nginx/html/data
    networks:
      - shared_network
      - docker
    ports:
      - "80:80"

networks:
  shared_network:
    external: false
  docker:
    name: docker_default

volumes:
  postgres_data: