version: '3'

services:
  postgres:
    image: kartoza/postgis:13-3.1
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  jupyter:
    build: ./jupyter
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - AWS_NO_SIGN_REQUEST=true
      - STAC_API_URL=https://explorer.sandbox.dea.ga.gov.au/stac/
      - CIABPASSWORD=${CIABPASSWORD:-secretpassword}
    ports:
      - "80:8888"
    volumes:
      - ./jupyter/notebooks:/jupyter/notebooks
      - ./jupyter/cuborizonte:/jupyter/cuborizonte
    restart: always
    depends_on:
      - postgres

  checkdb:
    image: schaffdev/port_check:latest
    environment:
      - CHECK_HOST=postgres
      - CHECK_PORT=5432

  django:
    build: ./django
    environment:
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=opendatacube
      - DJANGO_DB_USER=opendatacube
      - DJANGO_DB_PASSWORD=opendatacubepassword
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
    - postgres