services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - shared_network

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./datacube.conf:/etc/datacube.conf
      - ./data:/data
    environment:
      OWS_URL: http://ows:8000
      DATACUBE_CONFIG: /etc/datacube.conf
    restart: always
    depends_on:
      - postgres
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload"
    networks:
      - shared_network

  ows:
    image: opendatacube/ows:1.8.0-rc1
    build:
      context: ./ows
      dockerfile: Dockerfile
    mem_limit: 1g
    environment:
      ODC_DEFAULT_DB_HOSTNAME: postgres
      ODC_DEFAULT_DB_USERNAME: cuborizonte_user
      ODC_DEFAULT_DB_PASSWORD: opendatacubepassword
      ODC_DEFAULT_DB_DATABASE: cuborizonte_db
      ODC_DEFAULT_DB_PORT: 5432
      PYTHONPATH: /env/config
      DATACUBE_OWS_CFG: ows_refactored.dev_af_ows_root_cfg.ows_cfg
      ODC_CONFIG_PATH: /etc/datacube.conf
      CUBEDASH_URL_PREFIX: /cuborizonte/data-explorer/
    ports:
      - "8080:8080"  # Datacube Explorer
      - "8000:8000" 
    depends_on:
      - postgres
    volumes:
      - ./data:/data
      - ./ows/products:/env/products
      - ./ows/services/ows_refactored:/env/config/ows_refactored/
      - ./ows/services/inventory:/env/config/inventory/
      - ./ows/output:/env/config/output/
      - ./ows/handle_data_functions:/handle_data_functions
      - ./datacube.conf:/etc/datacube.conf
    networks:
      - shared_network
    command: >
      sh -c "
        sleep 30 &&
        datacube system init &&
        cubedash-gen --init --all &&
        gunicorn -b 0.0.0.0:8080 -w 4 'cubedash:create_app()' &
        gunicorn -b 0.0.0.0:8000 --workers=4 --timeout 120 'datacube_ows.wsgi:application'
      "  

  postgres:
    image: postgis/postgis:12-2.5-alpine
    mem_limit: 1g
    environment:
      POSTGRES_DB: cuborizonte_db
      POSTGRES_PASSWORD: opendatacubepassword
      POSTGRES_USER: cuborizonte_user
    volumes:
      - ./data:/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    networks:
      - shared_network

  checkdb:
    image: schaffdev/port_check:latest
    mem_limit: 500m
    environment:
      CHECK_HOST: postgres
      CHECK_PORT: 5432
    networks:
      - shared_network

  cuborizonte:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - frontend
      - backend
      - ows
    volumes:
      - ./data:/data
    networks:
      - shared_network
      - docker
    ports:
      - "80:80"

networks:
  shared_network:
    external: false
  docker:
    external: true
    name: docker_default


volumes:
  postgres_data: